<?php


namespace Bramus\Router;


class BlackRouter extends Router
{
    private $typeReq;

    public function get($pattern, $fn)
    {
        $this->typeReq = "get";
        parent::get($pattern, $fn); // TODO: Change the autogenerated stub
    }

    public function post($pattern, $fn)
    {
        $this->typeReq = "post";
        parent::post($pattern, $fn); // TODO: Change the autogenerated stub
    }

    public function put($pattern, $fn)
    {
        $this->typeReq = "put";
        parent::put($pattern, $fn); // TODO: Change the autogenerated stub
    }

    public function match($methods, $pattern, $fn)
    {
        $this->typeReq = "match";
        parent::match($methods, $pattern, $fn); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getTypeReq()
    {
        return $this->typeReq;
    }

}